services:
  postgres-test:
    image: postgres:17.6
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./infra/migrations:/migrations
    working_dir: /migrations
    depends_on:
      postgres-test:
        condition: service_healthy

  postgres-client:
    image: postgres:17.6
    depends_on:
      postgres-test:
        condition: service_healthy
    entrypoint:
      ["psql", "-h", "postgres-test", "-U", "testuser", "-d", "testdb"]
