services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtualstaging
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.2
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio-data:/data
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - APP_ENV=dev
      - AUTH0_AUDIENCE=https://api.virtualstaging.local
      - AUTH0_DOMAIN=dev-sleeping-pandas.us.auth0.com
      - JOB_QUEUE_NAME=default
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
      - PGDATABASE=virtualstaging
      - PGHOST=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - REDIS_ADDR=redis:6379
      - S3_ACCESS_KEY=minioadmin
      - S3_BUCKET=virtual-staging
      - S3_ENDPOINT=http://minio:9000
      - S3_PUBLIC_ENDPOINT=http://localhost:9000
      - S3_REGION=us-west-1
      - S3_SECRET_KEY=minioadmin
      - S3_USE_PATH_STYLE=true
    depends_on: [postgres, redis, minio]
    ports: ["8080:8080"]
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - APP_ENV=dev
      - JOB_QUEUE_NAME=default
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
      - PGDATABASE=virtualstaging
      - PGHOST=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - REDIS_ADDR=redis:6379
      - S3_ACCESS_KEY=minioadmin
      - S3_BUCKET=virtual-staging
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-west-1
      - S3_SECRET_KEY=minioadmin
      - S3_USE_PATH_STYLE=true
    depends_on: [postgres, redis, minio]
  otel:
    image: otel/opentelemetry-collector:0.133.0
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./infra/otelcol.yaml:/etc/otelcol-config.yaml
    ports: ["4317:4317", "4318:4318"]
  migrate:
    image: migrate/migrate
    volumes:
      - ./infra/migrations:/migrations
    working_dir: /migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  minio-data:
