services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtualstaging
    ports: ["5432:5432"]
  redis:
    image: redis:8.2
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio-data:/data
  api:
    build: ./apps/api
    environment:
      - APP_ENV=dev
      - AUTH0_DOMAIN=dev-sleeping-pandas.us.auth0.com
      - AUTH0_AUDIENCE=https://api.virtualstaging.local
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=virtualstaging
      - REDIS_ADDR=redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-west-1
      - S3_BUCKET=virtual-staging
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_USE_PATH_STYLE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
    depends_on: [postgres, redis, minio]
    ports: ["8080:8080"]
  worker:
    build: ./apps/worker
    environment:
      - APP_ENV=dev
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=virtualstaging
      - REDIS_ADDR=redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-west-1
      - S3_BUCKET=virtual-staging
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_USE_PATH_STYLE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
    depends_on: [postgres, redis, minio]
  otel:
    image: otel/opentelemetry-collector:0.133.0
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./infra/otelcol.yaml:/etc/otelcol-config.yaml
    ports: ["4317:4317", "4318:4318"]
volumes:
  minio-data:
