// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"sync"
)

// Ensure, that PgxPoolMock does implement PgxPool.
// If this is not the case, regenerate this file with moq.
var _ PgxPool = &PgxPoolMock{}

// PgxPoolMock is a mock implementation of PgxPool.
//
//	func TestSomethingThatUsesPgxPool(t *testing.T) {
//
//		// make and configure a mocked PgxPool
//		mockedPgxPool := &PgxPoolMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			ExecFunc: func(ctx context.Context, sql string, args ...interface{}) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//			QueryFunc: func(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
//				panic("mock out the Query method")
//			},
//			QueryRowFunc: func(ctx context.Context, sql string, args ...interface{}) pgx.Row {
//				panic("mock out the QueryRow method")
//			},
//		}
//
//		// use mockedPgxPool in code that requires PgxPool
//		// and then make assertions.
//
//	}
type PgxPoolMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, sql string, args ...interface{}) (pgconn.CommandTag, error)

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)

	// QueryRowFunc mocks the QueryRow method.
	QueryRowFunc func(ctx context.Context, sql string, args ...interface{}) pgx.Row

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []interface{}
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []interface{}
		}
		// QueryRow holds details about calls to the QueryRow method.
		QueryRow []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []interface{}
		}
	}
	lockClose    sync.RWMutex
	lockExec     sync.RWMutex
	lockPing     sync.RWMutex
	lockQuery    sync.RWMutex
	lockQueryRow sync.RWMutex
}

// Close calls CloseFunc.
func (mock *PgxPoolMock) Close() {
	if mock.CloseFunc == nil {
		panic("PgxPoolMock.CloseFunc: method is nil but PgxPool.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPgxPool.CloseCalls())
func (mock *PgxPoolMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Exec calls ExecFunc.
func (mock *PgxPoolMock) Exec(ctx context.Context, sql string, args ...interface{}) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("PgxPoolMock.ExecFunc: method is nil but PgxPool.Exec was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, sql, args...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedPgxPool.ExecCalls())
func (mock *PgxPoolMock) ExecCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []interface{}
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *PgxPoolMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("PgxPoolMock.PingFunc: method is nil but PgxPool.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedPgxPool.PingCalls())
func (mock *PgxPoolMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *PgxPoolMock) Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
	if mock.QueryFunc == nil {
		panic("PgxPoolMock.QueryFunc: method is nil but PgxPool.Query was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, sql, args...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedPgxPool.QueryCalls())
func (mock *PgxPoolMock) QueryCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []interface{}
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// QueryRow calls QueryRowFunc.
func (mock *PgxPoolMock) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	if mock.QueryRowFunc == nil {
		panic("PgxPoolMock.QueryRowFunc: method is nil but PgxPool.QueryRow was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockQueryRow.Lock()
	mock.calls.QueryRow = append(mock.calls.QueryRow, callInfo)
	mock.lockQueryRow.Unlock()
	return mock.QueryRowFunc(ctx, sql, args...)
}

// QueryRowCalls gets all the calls that were made to QueryRow.
// Check the length with:
//
//	len(mockedPgxPool.QueryRowCalls())
func (mock *PgxPoolMock) QueryRowCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []interface{}
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []interface{}
	}
	mock.lockQueryRow.RLock()
	calls = mock.calls.QueryRow
	mock.lockQueryRow.RUnlock()
	return calls
}
