name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/web/api/v1/**'
      - 'apps/docs/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs dependencies
        run: |
          cd apps/docs
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          cd apps/docs
          mkdocs build

      - name: Validate OpenAPI spec
        run: make docs-validate

      - name: Combine documentation sites
        run: |
          mkdir -p _site
          # Copy MkDocs site as root
          cp -r apps/docs/site/* _site/
          # Copy OpenAPI docs to /api subdirectory
          mkdir -p _site/api
          cp -r apps/api/web/api/v1/* _site/api/

      - name: Upload combined site
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
