// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package image

import (
	"context"
	"github.com/virtual-staging-ai/api/internal/storage/queries"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			CreateImageFunc: func(ctx context.Context, req *CreateImageRequest) (*Image, error) {
//				panic("mock out the CreateImage method")
//			},
//			DeleteImageFunc: func(ctx context.Context, imageID string) error {
//				panic("mock out the DeleteImage method")
//			},
//			GetImageByIDFunc: func(ctx context.Context, imageID string) (*Image, error) {
//				panic("mock out the GetImageByID method")
//			},
//			GetImagesByProjectIDFunc: func(ctx context.Context, projectID string) ([]*Image, error) {
//				panic("mock out the GetImagesByProjectID method")
//			},
//			GetProjectCostSummaryFunc: func(ctx context.Context, projectID string) (*ProjectCostSummary, error) {
//				panic("mock out the GetProjectCostSummary method")
//			},
//			UpdateImageStatusFunc: func(ctx context.Context, imageID string, status Status) (*Image, error) {
//				panic("mock out the UpdateImageStatus method")
//			},
//			UpdateImageWithErrorFunc: func(ctx context.Context, imageID string, errorMsg string) (*Image, error) {
//				panic("mock out the UpdateImageWithError method")
//			},
//			UpdateImageWithStagedURLFunc: func(ctx context.Context, imageID string, stagedURL string) (*Image, error) {
//				panic("mock out the UpdateImageWithStagedURL method")
//			},
//			convertToImageFunc: func(dbImage *queries.Image) *Image {
//				panic("mock out the convertToImage method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// CreateImageFunc mocks the CreateImage method.
	CreateImageFunc func(ctx context.Context, req *CreateImageRequest) (*Image, error)

	// DeleteImageFunc mocks the DeleteImage method.
	DeleteImageFunc func(ctx context.Context, imageID string) error

	// GetImageByIDFunc mocks the GetImageByID method.
	GetImageByIDFunc func(ctx context.Context, imageID string) (*Image, error)

	// GetImagesByProjectIDFunc mocks the GetImagesByProjectID method.
	GetImagesByProjectIDFunc func(ctx context.Context, projectID string) ([]*Image, error)

	// GetProjectCostSummaryFunc mocks the GetProjectCostSummary method.
	GetProjectCostSummaryFunc func(ctx context.Context, projectID string) (*ProjectCostSummary, error)

	// UpdateImageStatusFunc mocks the UpdateImageStatus method.
	UpdateImageStatusFunc func(ctx context.Context, imageID string, status Status) (*Image, error)

	// UpdateImageWithErrorFunc mocks the UpdateImageWithError method.
	UpdateImageWithErrorFunc func(ctx context.Context, imageID string, errorMsg string) (*Image, error)

	// UpdateImageWithStagedURLFunc mocks the UpdateImageWithStagedURL method.
	UpdateImageWithStagedURLFunc func(ctx context.Context, imageID string, stagedURL string) (*Image, error)

	// convertToImageFunc mocks the convertToImage method.
	convertToImageFunc func(dbImage *queries.Image) *Image

	// calls tracks calls to the methods.
	calls struct {
		// CreateImage holds details about calls to the CreateImage method.
		CreateImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *CreateImageRequest
		}
		// DeleteImage holds details about calls to the DeleteImage method.
		DeleteImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID string
		}
		// GetImageByID holds details about calls to the GetImageByID method.
		GetImageByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID string
		}
		// GetImagesByProjectID holds details about calls to the GetImagesByProjectID method.
		GetImagesByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
		}
		// GetProjectCostSummary holds details about calls to the GetProjectCostSummary method.
		GetProjectCostSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
		}
		// UpdateImageStatus holds details about calls to the UpdateImageStatus method.
		UpdateImageStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID string
			// Status is the status argument value.
			Status Status
		}
		// UpdateImageWithError holds details about calls to the UpdateImageWithError method.
		UpdateImageWithError []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID string
			// ErrorMsg is the errorMsg argument value.
			ErrorMsg string
		}
		// UpdateImageWithStagedURL holds details about calls to the UpdateImageWithStagedURL method.
		UpdateImageWithStagedURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID string
			// StagedURL is the stagedURL argument value.
			StagedURL string
		}
		// convertToImage holds details about calls to the convertToImage method.
		convertToImage []struct {
			// DbImage is the dbImage argument value.
			DbImage *queries.Image
		}
	}
	lockCreateImage              sync.RWMutex
	lockDeleteImage              sync.RWMutex
	lockGetImageByID             sync.RWMutex
	lockGetImagesByProjectID     sync.RWMutex
	lockGetProjectCostSummary    sync.RWMutex
	lockUpdateImageStatus        sync.RWMutex
	lockUpdateImageWithError     sync.RWMutex
	lockUpdateImageWithStagedURL sync.RWMutex
	lockconvertToImage           sync.RWMutex
}

// CreateImage calls CreateImageFunc.
func (mock *ServiceMock) CreateImage(ctx context.Context, req *CreateImageRequest) (*Image, error) {
	if mock.CreateImageFunc == nil {
		panic("ServiceMock.CreateImageFunc: method is nil but Service.CreateImage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *CreateImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateImage.Lock()
	mock.calls.CreateImage = append(mock.calls.CreateImage, callInfo)
	mock.lockCreateImage.Unlock()
	return mock.CreateImageFunc(ctx, req)
}

// CreateImageCalls gets all the calls that were made to CreateImage.
// Check the length with:
//
//	len(mockedService.CreateImageCalls())
func (mock *ServiceMock) CreateImageCalls() []struct {
	Ctx context.Context
	Req *CreateImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *CreateImageRequest
	}
	mock.lockCreateImage.RLock()
	calls = mock.calls.CreateImage
	mock.lockCreateImage.RUnlock()
	return calls
}

// DeleteImage calls DeleteImageFunc.
func (mock *ServiceMock) DeleteImage(ctx context.Context, imageID string) error {
	if mock.DeleteImageFunc == nil {
		panic("ServiceMock.DeleteImageFunc: method is nil but Service.DeleteImage was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ImageID string
	}{
		Ctx:     ctx,
		ImageID: imageID,
	}
	mock.lockDeleteImage.Lock()
	mock.calls.DeleteImage = append(mock.calls.DeleteImage, callInfo)
	mock.lockDeleteImage.Unlock()
	return mock.DeleteImageFunc(ctx, imageID)
}

// DeleteImageCalls gets all the calls that were made to DeleteImage.
// Check the length with:
//
//	len(mockedService.DeleteImageCalls())
func (mock *ServiceMock) DeleteImageCalls() []struct {
	Ctx     context.Context
	ImageID string
} {
	var calls []struct {
		Ctx     context.Context
		ImageID string
	}
	mock.lockDeleteImage.RLock()
	calls = mock.calls.DeleteImage
	mock.lockDeleteImage.RUnlock()
	return calls
}

// GetImageByID calls GetImageByIDFunc.
func (mock *ServiceMock) GetImageByID(ctx context.Context, imageID string) (*Image, error) {
	if mock.GetImageByIDFunc == nil {
		panic("ServiceMock.GetImageByIDFunc: method is nil but Service.GetImageByID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ImageID string
	}{
		Ctx:     ctx,
		ImageID: imageID,
	}
	mock.lockGetImageByID.Lock()
	mock.calls.GetImageByID = append(mock.calls.GetImageByID, callInfo)
	mock.lockGetImageByID.Unlock()
	return mock.GetImageByIDFunc(ctx, imageID)
}

// GetImageByIDCalls gets all the calls that were made to GetImageByID.
// Check the length with:
//
//	len(mockedService.GetImageByIDCalls())
func (mock *ServiceMock) GetImageByIDCalls() []struct {
	Ctx     context.Context
	ImageID string
} {
	var calls []struct {
		Ctx     context.Context
		ImageID string
	}
	mock.lockGetImageByID.RLock()
	calls = mock.calls.GetImageByID
	mock.lockGetImageByID.RUnlock()
	return calls
}

// GetImagesByProjectID calls GetImagesByProjectIDFunc.
func (mock *ServiceMock) GetImagesByProjectID(ctx context.Context, projectID string) ([]*Image, error) {
	if mock.GetImagesByProjectIDFunc == nil {
		panic("ServiceMock.GetImagesByProjectIDFunc: method is nil but Service.GetImagesByProjectID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockGetImagesByProjectID.Lock()
	mock.calls.GetImagesByProjectID = append(mock.calls.GetImagesByProjectID, callInfo)
	mock.lockGetImagesByProjectID.Unlock()
	return mock.GetImagesByProjectIDFunc(ctx, projectID)
}

// GetImagesByProjectIDCalls gets all the calls that were made to GetImagesByProjectID.
// Check the length with:
//
//	len(mockedService.GetImagesByProjectIDCalls())
func (mock *ServiceMock) GetImagesByProjectIDCalls() []struct {
	Ctx       context.Context
	ProjectID string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
	}
	mock.lockGetImagesByProjectID.RLock()
	calls = mock.calls.GetImagesByProjectID
	mock.lockGetImagesByProjectID.RUnlock()
	return calls
}

// GetProjectCostSummary calls GetProjectCostSummaryFunc.
func (mock *ServiceMock) GetProjectCostSummary(ctx context.Context, projectID string) (*ProjectCostSummary, error) {
	if mock.GetProjectCostSummaryFunc == nil {
		panic("ServiceMock.GetProjectCostSummaryFunc: method is nil but Service.GetProjectCostSummary was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockGetProjectCostSummary.Lock()
	mock.calls.GetProjectCostSummary = append(mock.calls.GetProjectCostSummary, callInfo)
	mock.lockGetProjectCostSummary.Unlock()
	return mock.GetProjectCostSummaryFunc(ctx, projectID)
}

// GetProjectCostSummaryCalls gets all the calls that were made to GetProjectCostSummary.
// Check the length with:
//
//	len(mockedService.GetProjectCostSummaryCalls())
func (mock *ServiceMock) GetProjectCostSummaryCalls() []struct {
	Ctx       context.Context
	ProjectID string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
	}
	mock.lockGetProjectCostSummary.RLock()
	calls = mock.calls.GetProjectCostSummary
	mock.lockGetProjectCostSummary.RUnlock()
	return calls
}

// UpdateImageStatus calls UpdateImageStatusFunc.
func (mock *ServiceMock) UpdateImageStatus(ctx context.Context, imageID string, status Status) (*Image, error) {
	if mock.UpdateImageStatusFunc == nil {
		panic("ServiceMock.UpdateImageStatusFunc: method is nil but Service.UpdateImageStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ImageID string
		Status  Status
	}{
		Ctx:     ctx,
		ImageID: imageID,
		Status:  status,
	}
	mock.lockUpdateImageStatus.Lock()
	mock.calls.UpdateImageStatus = append(mock.calls.UpdateImageStatus, callInfo)
	mock.lockUpdateImageStatus.Unlock()
	return mock.UpdateImageStatusFunc(ctx, imageID, status)
}

// UpdateImageStatusCalls gets all the calls that were made to UpdateImageStatus.
// Check the length with:
//
//	len(mockedService.UpdateImageStatusCalls())
func (mock *ServiceMock) UpdateImageStatusCalls() []struct {
	Ctx     context.Context
	ImageID string
	Status  Status
} {
	var calls []struct {
		Ctx     context.Context
		ImageID string
		Status  Status
	}
	mock.lockUpdateImageStatus.RLock()
	calls = mock.calls.UpdateImageStatus
	mock.lockUpdateImageStatus.RUnlock()
	return calls
}

// UpdateImageWithError calls UpdateImageWithErrorFunc.
func (mock *ServiceMock) UpdateImageWithError(ctx context.Context, imageID string, errorMsg string) (*Image, error) {
	if mock.UpdateImageWithErrorFunc == nil {
		panic("ServiceMock.UpdateImageWithErrorFunc: method is nil but Service.UpdateImageWithError was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ImageID  string
		ErrorMsg string
	}{
		Ctx:      ctx,
		ImageID:  imageID,
		ErrorMsg: errorMsg,
	}
	mock.lockUpdateImageWithError.Lock()
	mock.calls.UpdateImageWithError = append(mock.calls.UpdateImageWithError, callInfo)
	mock.lockUpdateImageWithError.Unlock()
	return mock.UpdateImageWithErrorFunc(ctx, imageID, errorMsg)
}

// UpdateImageWithErrorCalls gets all the calls that were made to UpdateImageWithError.
// Check the length with:
//
//	len(mockedService.UpdateImageWithErrorCalls())
func (mock *ServiceMock) UpdateImageWithErrorCalls() []struct {
	Ctx      context.Context
	ImageID  string
	ErrorMsg string
} {
	var calls []struct {
		Ctx      context.Context
		ImageID  string
		ErrorMsg string
	}
	mock.lockUpdateImageWithError.RLock()
	calls = mock.calls.UpdateImageWithError
	mock.lockUpdateImageWithError.RUnlock()
	return calls
}

// UpdateImageWithStagedURL calls UpdateImageWithStagedURLFunc.
func (mock *ServiceMock) UpdateImageWithStagedURL(ctx context.Context, imageID string, stagedURL string) (*Image, error) {
	if mock.UpdateImageWithStagedURLFunc == nil {
		panic("ServiceMock.UpdateImageWithStagedURLFunc: method is nil but Service.UpdateImageWithStagedURL was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ImageID   string
		StagedURL string
	}{
		Ctx:       ctx,
		ImageID:   imageID,
		StagedURL: stagedURL,
	}
	mock.lockUpdateImageWithStagedURL.Lock()
	mock.calls.UpdateImageWithStagedURL = append(mock.calls.UpdateImageWithStagedURL, callInfo)
	mock.lockUpdateImageWithStagedURL.Unlock()
	return mock.UpdateImageWithStagedURLFunc(ctx, imageID, stagedURL)
}

// UpdateImageWithStagedURLCalls gets all the calls that were made to UpdateImageWithStagedURL.
// Check the length with:
//
//	len(mockedService.UpdateImageWithStagedURLCalls())
func (mock *ServiceMock) UpdateImageWithStagedURLCalls() []struct {
	Ctx       context.Context
	ImageID   string
	StagedURL string
} {
	var calls []struct {
		Ctx       context.Context
		ImageID   string
		StagedURL string
	}
	mock.lockUpdateImageWithStagedURL.RLock()
	calls = mock.calls.UpdateImageWithStagedURL
	mock.lockUpdateImageWithStagedURL.RUnlock()
	return calls
}

// convertToImage calls convertToImageFunc.
func (mock *ServiceMock) convertToImage(dbImage *queries.Image) *Image {
	if mock.convertToImageFunc == nil {
		panic("ServiceMock.convertToImageFunc: method is nil but Service.convertToImage was just called")
	}
	callInfo := struct {
		DbImage *queries.Image
	}{
		DbImage: dbImage,
	}
	mock.lockconvertToImage.Lock()
	mock.calls.convertToImage = append(mock.calls.convertToImage, callInfo)
	mock.lockconvertToImage.Unlock()
	return mock.convertToImageFunc(dbImage)
}

// convertToImageCalls gets all the calls that were made to convertToImage.
// Check the length with:
//
//	len(mockedService.convertToImageCalls())
func (mock *ServiceMock) convertToImageCalls() []struct {
	DbImage *queries.Image
} {
	var calls []struct {
		DbImage *queries.Image
	}
	mock.lockconvertToImage.RLock()
	calls = mock.calls.convertToImage
	mock.lockconvertToImage.RUnlock()
	return calls
}
